import Bakes from "../images/bakes.png";
import TechEase from "../images/techease.png";
import Cosmetic from "../images/cosmetic.png";
import Blossom from "../images/blossom.png";
import Health from "../images/health.png";

export const item1 = [
  {
    id: 1,
    name: "Blissful Bakes",
    description: "Sweet Haven Bakery",
    img: Bakes,
    amountRaised: "$80,000",
    numberOfInvestor: 5,
    minInvest: "$10,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 2,
    name: "TechEase Solutions",
    description: "TechHub Solutions",
    img: TechEase,
    amountRaised: "$90,000",
    numberOfInvestor: 10,
    minInvest: "$10,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 3,
    name: "TechEase Solutions",
    description: "TechHub Solutions",
    img: TechEase,
    amountRaised: "$90,000",
    numberOfInvestor: 10,
    minInvest: "$10,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 4,
    name: "Blissful Bakes",
    description: "Sweet Haven Bakery",
    img: Bakes,
    amountRaised: "$80,000",
    numberOfInvestor: 5,
    minInvest: "$10,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 5,
    name: "Cosmetic Stores",
    description: "Urban centres",
    img: Cosmetic,
    amountRaised: "$50,000",
    numberOfInvestor: 10,
    minInvest: "$10,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 6,
    name: " Blossom Boutique",
    description: "Bloomingdale Flower Market",
    img: Blossom,
    amountRaised: "$400,500",
    numberOfInvestor: 5,
    minInvest: "$40,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 7,
    name: " Blossom Boutique",
    description: "Bloomingdale Flower Market",
    img: Blossom,
    amountRaised: "$400,500",
    numberOfInvestor: 5,
    minInvest: "$40,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 8,
    name: " Blossom Boutique",
    description: "Bloomingdale Flower Market",
    img: Blossom,
    amountRaised: "$400,500",
    numberOfInvestor: 5,
    minInvest: "$40,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 9,
    name: " Blossom Boutique",
    description: "Bloomingdale Flower Market",
    img: Blossom,
    amountRaised: "$400,500",
    numberOfInvestor: 5,
    minInvest: "$40,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
];

export const item2 = [
  {
    id: 1,
    name: "Health and Wellness Services",
    description: "Los Angeles, California,",
    img: Health,
    amountRaised: "$100,000",
    numberOfInvestor: 5,
    minInvest: "$10,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 2,
    name: "TechEase Solutions",
    description: "TechHub Solutions",
    img: TechEase,
    amountRaised: "$90,000",
    numberOfInvestor: 10,
    minInvest: "$10,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 3,
    name: "TechEase Solutions",
    description: "TechHub Solutions",
    img: TechEase,
    amountRaised: "$90,000",
    numberOfInvestor: 10,
    minInvest: "$10,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 4,
    name: "Blissful Bakes",
    description: "Sweet Haven Bakery",
    img: Bakes,
    amountRaised: "$80,000",
    numberOfInvestor: 5,
    minInvest: "$10,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 5,
    name: "Cosmetic Stores",
    description: "Urban centres",
    img: Cosmetic,
    amountRaised: "$50,000",
    numberOfInvestor: 10,
    minInvest: "$10,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 6,
    name: " Blossom Boutique",
    description: "Bloomingdale Flower Market",
    img: Blossom,
    amountRaised: "$400,500",
    numberOfInvestor: 5,
    minInvest: "$40,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 7,
    name: " Blossom Boutique",
    description: "Bloomingdale Flower Market",
    img: Blossom,
    amountRaised: "$400,500",
    numberOfInvestor: 5,
    minInvest: "$40,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 8,
    name: " Blossom Boutique",
    description: "Bloomingdale Flower Market",
    img: Blossom,
    amountRaised: "$400,500",
    numberOfInvestor: 5,
    minInvest: "$40,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 9,
    name: " Blossom Boutique",
    description: "Bloomingdale Flower Market",
    img: Blossom,
    amountRaised: "$400,500",
    numberOfInvestor: 5,
    minInvest: "$40,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 10,
    name: " Blossom Boutique",
    description: "Bloomingdale Flower Market",
    img: Blossom,
    amountRaised: "$400,500",
    numberOfInvestor: 5,
    minInvest: "$40,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 11,
    name: " Blossom Boutique",
    description: "Bloomingdale Flower Market",
    img: Blossom,
    amountRaised: "$400,500",
    numberOfInvestor: 5,
    minInvest: "$40,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 12,
    name: " Blossom Boutique",
    description: "Bloomingdale Flower Market",
    img: Blossom,
    amountRaised: "$400,500",
    numberOfInvestor: 5,
    minInvest: "$40,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 13,
    name: " Blossom Boutique",
    description: "Bloomingdale Flower Market",
    img: Blossom,
    amountRaised: "$400,500",
    numberOfInvestor: 5,
    minInvest: "$40,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 14,
    name: " Blossom Boutique",
    description: "Bloomingdale Flower Market",
    img: Blossom,
    amountRaised: "$400,500",
    numberOfInvestor: 5,
    minInvest: "$40,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 15,
    name: " Blossom Boutique",
    description: "Bloomingdale Flower Market",
    img: Blossom,
    amountRaised: "$400,500",
    numberOfInvestor: 5,
    minInvest: "$40,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
  {
    id: 16,
    name: " Blossom Boutique",
    description: "Bloomingdale Flower Market",
    img: Blossom,
    amountRaised: "$400,500",
    numberOfInvestor: 5,
    minInvest: "$40,000",
    Raised: "Raised",
    Investors: "Investors",
    MinInvestment: "Min.Investment",
  },
];

export const tran = [
  {
    id: 1,
    name: "Blissfull bakes",
    percent: "10%",
    amount: "$30,000",
  },
  {
    id: 2,
    name: "TechEase Solutions",
    percent: "20%",
    amount: "$50,000",
  },
  {
    id: 3,
    name: "Blissfull bakes",
    percent: "10%",
    amount: "$20,000",
  },
];
